- name: Ensure {{ package_name }} directory exists
  become: true
  file:
    path: "/opt/{{ package_name }}/"
    state: "directory"
    owner: root
    group: root
    mode: 0755

- name: Verify current version is installed
  become: true
  file:
    path: "/opt/{{ package_name }}/{{ package_name }}-{{ package_version }}"
    state: "file"
    owner: root
    group: root
    mode: 0755
  ignore_errors: true
  register: verify

- name: Fetch {{ package_name }} archive
  become: true
  get_url:
    url: "{{ package_fetch_url }}"
    dest: "/tmp/{{ package_name }}.zip"
    owner: root
    group: root
    mode: 0644
  when: verify.failed

- name: Unarchive {{ package_name }}
  become: true
  unarchive:
    remote_src: true
    src: "/tmp/{{ package_name }}.zip"
    dest: "/opt/{{ package_name }}/"
  when: verify.failed

- name: Copy to versioned naming
  become: true
  copy:
    remote_src: true
    src: "/opt/{{ package_name }}/{{ package_name }}"
    dest: "/opt/{{ package_name }}/{{ package_name }}-{{ package_version }}"
    owner: root
    group: root
    mode: 0755
  when: verify.failed

- name: Ensure extracted executable is absent
  file:
    path: "/opt/{{ package_name }}/{{ package_name }}"
    state: "absent"

- name: Link versioned executable to active
  file:
    path: "/usr/local/bin/{{ package_name }}"
    src: "/opt/{{ package_name }}/{{ package_name }}-{{ package_version }}"
    state: "link"
