- name: ensure the tridactyl rc dirs exist
  become: false
  file:
    path: "{{ item }}"
    state: directory
  loop:
  - "{{ home_folder }}/.config/tridactyl/"
  - "{{ home_folder }}/.config/tridactyl/themes/"
  tags: dots

- name: template tridactyl conf
  become: false
  template:
    src: tridactylrc
    dest: "{{ home_folder }}/.config/tridactyl/tridactylrc"
  tags: dots

- name: "template tridactyl theme to ~/.config/{{ theme_name }}.css"
  become: false
  template:
    src: firefox-tridactyl.css
    dest: "{{ home_folder }}/.config/tridactyl/themes/{{ theme_name }}.css"
  tags:
  - theme
  - dots

- name: Alert user for manual action
  debug:
    msg: |
      Ensure to run :nativeinstall on tridactyl to load the rc.
      Run :colorscheme {{ theme_name }} to (re)load the theme
