- name: Ensure terraform directory exists
  become: true
  file:
    path: "/opt/terraform/"
    state: "directory"
    owner: root
    group: root
    mode: 0755

- name: Verify current version is installed
  become: true
  file:
    path: "/opt/terraform/terraform-{{ terraform_version }}"
    state: "file"
    owner: root
    group: root
    mode: 0755
  ignore_errors: true
  register: verify

- name: Fetch terraform archive
  become: true
  get_url:
    url: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
    dest: "/tmp/terraform.zip"
    owner: root
    group: root
    mode: 0644
  when: verify.failed

- name: Unarchive terraform
  become: true
  unarchive:
    remote_src: true
    src: "/tmp/terraform.zip"
    dest: "/opt/terraform/"
  when: verify.failed

- name: Copy to versioned naming
  become: true
  copy:
    remote_src: true
    src: "/opt/terraform/terraform"
    dest: "/opt/terraform/terraform-{{ terraform_version }}"
    owner: root
    group: root
    mode: 0755
  when: verify.failed

- name: Ensure extracted executable is absent
  file:
    path: "/opt/terraform/terraform"
    state: "absent"

- name: Link versioned executable to active
  file:
    path: "/usr/local/bin/terraform"
    src: "/opt/terraform/terraform-{{ terraform_version }}"
    state: "link"
