- name: Install packages
  package:
    name:
    - "niri"
    - "fuzzel"
    - "dunst"
    - "swaylock"
    - "swaybg"
    - "wl-clipboard"
    - "xwayland-satellite"
    - "waybar"
    state: present

- name: Ensure configuration dirs exist
  become: false
  file:
    path: "{{ home_folder }}/.config/{{ item }}"
    state: directory
    mode: 0750
  loop:
  - niri
  - waybar
  - fuzzel

- name: Template configuration
  become: false
  template:
    src: "{{ item }}"
    dest: "{{ home_folder }}/.config/{{ item }}"
  loop:
  - niri/config.kdl
  - waybar/config.jsonc
  - waybar/style.css
  - fuzzel/fuzzel.ini
