- name: Install packages
  package:
    name:
    - "niri"
    - "fuzzel"
    - "dunst"
    - "swaylock"
    - "swaybg"
    - "wl-clipboard"
    - "xwayland-satellite"
    state: present

- name: Ensure niri configuration dir exists
  become: false
  file:
    path: "{{ home_folder }}/.config/niri"
    state: directory
    mode: 0750

- name: Template niri configuration
  become: false
  template:
    src: config.kdl.j2
    dest: "{{ home_folder }}/.config/niri/config.kdl"
