alias emacs='emacs -nw'
alias git-log='git log --oneline --decorate --graph --all'
alias trc='transmission-remote-cli'
alias cgrep='grep --color=always'
alias grep='grep --color=auto'
alias less='less -R'
alias screendev='screen -c ~/.screendevrc'
alias vimdev='vim -u ~/.vimdevrc'
alias vimd='vim -u ~/.vimdevrc'
alias vimj='vim -u ~/.vimjrc'
alias ncmpcphome='ncmpcpp -c ~/.ncmpcpp/config_server'
alias ls='ls --literal --color=auto'
alias lk='ls --color=never'
alias info='info --vi-keys'
