alias emacs='emacs -nw'
alias git-log='git log --oneline --decorate --graph'
alias trc='transmission-remote-cli'
alias cgrep='grep --color=always'
alias grep='grep --color=auto'
alias less='less -R'
alias vimdev='vim -u ~/.vimdevrc'
alias ncmpcphome='ncmpcpp -c ~/.ncmpcpp/config_server'
