- name: install packages
  package:
    name: rxvt-unicode
    state: latest

- name: gather package facts
  package_facts: {}

- name: template {{ item.dest }}
  become: false
  template:
    src: "{{ item.template }}"
    dest: "{{ home_folder }}/{{ item.dest }}"
  with_items:
  - template: "Xdefaults.j2"
    dest: ".Xdefaults"
  - template: "Xresources.j2"
    dest: ".Xresources"
  tags:
  - theme

- name: template Xorg configuration
  become: true
  template:
    src: "xorg/{{ item }}.conf.j2"
    dest: "/etc/X11/xorg.conf.d/{{ item }}.conf"
    owner: "root"
    group: "root"
    mode: 0644
  loop:
  - touchpad
  - keyboard
  - display

  # this is here because it fits with the external device configuration.
- name: template systemd-logind configuration
  become: true
  template:
    src: "logind.conf"
    dest: "/etc/systemd/logind.conf"
    owner: "root"
    group: "root"
    mode: 0644
