- name: install desktop packages
  apt:
    name: [
      "herbstluftwm", "dzen2", "nitrogen",
      "sxiv", "picom", "scrot", "maim",
      "xsel", "pavucontrol", "i3lock-fancy",
      "autorandr", "brightnessctl"
    ]
    state: latest

- name: ensure the user is in the video group
  user:
    name: "{{ default_user }}"
    append: true
    groups: [ "video" ]

- name: ensure herbstluftwm config directory exists
  become: false
  file:
    path: "{{ home_folder }}/.config/herbstluftwm"
    state: directory

- name: template picom configuration
  become: false
  template:
    src: "picom.j2.conf"
    dest: "{{ home_folder }}/.config/picom.conf"

- name: template herbstluftwm configuration
  become: false
  template:
    src: "autostart.j2.sh"
    dest: "{{ home_folder }}/.config/herbstluftwm/autostart"
    mode: 0755
  notify: reload herbstluftwm
  tags:
  - theme

- import_tasks: notifications.yml
