- name: install desktop packages
  package:
    name: [
      "herbstluftwm", "dzen2", "nitrogen",
      "sxiv", "maim",
      "xsel", "pavucontrol", "{{ hlwm_lock }}",
      "autorandr", "brightnessctl"
    ]
    state: latest

- name: gather package facts
  package_facts: {}
  tags: theme

- name: ensure the user is in the video group
  user:
    name: "{{ default_user }}"
    append: true
    groups: [ "video" ]

- name: ensure herbstluftwm config directory exists
  become: false
  file:
    path: "{{ home_folder }}/.config/herbstluftwm"
    state: directory

- name: template picom configuration
  become: false
  template:
    src: "picom.j2.conf"
    dest: "{{ home_folder }}/.config/picom.conf"

- name: template herbstluftwm configuration
  become: false
  template:
    src: "autostart.j2.sh"
    dest: "{{ home_folder }}/.config/herbstluftwm/autostart"
    mode: 0755
  notify: reload herbstluftwm
  tags:
  - theme

- name: ensure autorandr hook dir is present
  become: false
  file:
    path: "{{ home_folder }}/.config/autorandr/postswitch.d"
    state: "directory"
    mode: 0750

- name: install autorandr hook
  become: false
  template:
    src: "autorandr_notify.j2.sh"
    dest: "{{ home_folder }}/.config/autorandr/postswitch.d/notify.sh"
    mode: 0750

- import_tasks: notifications.yml
