" Use Vim settings, rather than Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

source ~/.vimpluginrc

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

set history=200 " lines of command line history to keep
set ruler       " show the cursor position all the time
set showcmd     " display incomplete commands
set incsearch   " do incremental searching

" In many terminal emulators the mouse works just fine, thus enable it.
if has('mouse')
    set mouse=a
endif

" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
if &t_Co > 2 || has("gui_running")
    syntax on
    set hlsearch
endif

if has("autocmd")
    " Enable file type detection.
    " Use the default filetype settings, so that mail gets 'tw' set to 72,
    " 'cindent' is on in C files, etc.
    " Also load indent files, to automatically do language-dependent indenting.
    filetype plugin indent on

    " Put these in an autocmd group, so that we can delete them easily.
    augroup vimrcEx
        au!
        " When editing a file, always jump to the last known cursor position.
        " Don't do it when the position is invalid or when inside an event handler
        " (happens when dropping a file on gvim).
        " Also don't do it when the mark is in the first line, that is the default
        " position when opening a file.
        autocmd BufReadPost *
                    \ if line("'\"") > 1 && line("'\"") <= line("$") |
                    \   exe "normal! g`\"" |
                    \ endif

    augroup END
else
    set autoindent		" always set autoindenting on
endif " has("autocmd")

set keymap=greek_utf-8 " keymaps: add greek, defaults
set iminsert=0
set imsearch=-1
set foldmethod=syntax  " enable folds
"Force 8 colors for 88color/256color terminals. We are humans, not mantis shrimps.
if &t_Co > 8
    set t_Co=8
endif

" No annoying vim files in my folders (Enabling adds features, e.g. cross-session undos)
set noswapfile
set noundofile
set nobackup
set nowritebackup

" Tab key shows as 4 characters, tab key inserts spaces, auto indentation 4 spaces.
set tabstop=4
set shiftwidth=4
set expandtab

" Set smart search (case sensitive only when capital letters in search phrase)
set ignorecase
set smartcase

set wildmenu " Visual menu on command autocomplete (on TAB, not Ctrl+d)

set hidden " Allow for buffer switching without being forced to save

if has("autocmd")
    " Support Format-Flowed when composing mail.
    autocmd FileType mail setlocal fo+=aw tw=72
    " When done autocompleting, close any preview windows
    autocmd CompleteDone * pclose
    " some ansible/jinja2 template overrides
    autocmd BufNewFile,BufRead *.yaml.*        set filetype=yaml
    autocmd BufNewFile,BufRead *.yml.*         set filetype=yaml
    autocmd BufNewFile,BufRead *.json.*        set filetype=json
    autocmd BufNewFile,BufRead *.properties.*  set filetype=jproperties
    autocmd BufNewFile,BufRead *.service.*     set filetype=systemd
endif

" Configure Theming

colorscheme slate
set number
set cursorline
highlight LineNr       cterm=NONE ctermfg=LightGrey ctermbg=Black
highlight Search       cterm=NONE ctermfg=White     ctermbg=DarkGrey
highlight MatchParen   cterm=NONE ctermfg=Black     ctermbg=Brown
highlight CursorLine   cterm=NONE                   ctermbg=NONE
highlight CursorLineNr cterm=NONE ctermfg=Black     ctermbg=Brown

set path=.,/usr/include,**,,
