---
- name: install dev packages
  become: "{{ package_manager_become }}"
  package:
    name:
    - "golang"
    - "python"
    - "mise"
    - "neovim"
    - "groovy"
    - "pipx"
    - "uv"
    state: "present"

- name: install node
  become: false
  shell: |
    mise use --global node@20
    mise use --global npm

- name: install rustup-init package
  become: "{{ package_manager_become }}"
  package:
    name:
    - "rustup"
  register: rust_fetch
