---
- name: install dev packages
  package:
    name:
    - "golang"
    - "python"
    - "julia"
    - "node"
    - "neovim"
    state: "present"

- name: install rustup-init package
  package:
    name:
    - "rustup-init"
  register: rust_fetch
