---
- name: add required apt repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
  loop:
  - "ppa:longsleep/golang-backports"

- name: install lang packages
  package:
    name:
    - "golang-go"
    - "python3"
    - "python3-pip"
    - "php"
    - "php-zip"
    - "php-curl"
    - "php-xml"
    - "nodejs"
    - "npm"
    state: "present"

- name: install uv python package manager
  include_role:
    name: packages/binpackages
  vars:
    binpackages_items:
    - name: uv
      version: "{{ python_uv_version }}"
      fetch_url: "https://github.com/astral-sh/uv/releases/download/{{ python_uv_version }}/uv-x86_64-unknown-linux-gnu.tar.gz"
      subpath: "uv-x86_64-unknown-linux-gnu"

- name: fetch rustup-init
  become: true
  get_url:
    url: "https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init"
    dest: "/usr/bin/rustup-init"
    force: false
    owner: root
    group: "{{ root_group }}"
    mode: 0755
  register: rust_fetch

- include_tasks: groovy.yml
  tags: language

- include_tasks: helix.yml

- name: install neovim bob package manager
  include_role:
    name: packages/binpackages
  vars:
    binpackages_items:
    - name: bob
      version: "{{ neovim_bob_version }}"
      subpath: "bob-linux-x86_64"
      fetch_url: "https://github.com/MordechaiHadad/bob/releases/download/v{{ neovim_bob_version }}/bob-linux-x86_64.zip"

- name: install neovim via bob
  shell: >
    bob install {{ neovim_version }} && bob use {{ neovim_version }}

- name: link nvim to path
  become: true
  file:
    path: "/usr/bin/nvim"
    src: "{{ home_folder }}/.local/share/bob/nvim-bin/nvim"
    state: "link"
