---
- name: install lang packages
  package:
    name:
    - "golang-go"
    - "python3"
    - "python3-pip"
    - "julia"
    state: "present"

- name: fetch rustup-init
  become: true
  get_url:
    url: "https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init"
    dest: "/opt/rustup-init"
    force: false
    owner: root
    group: "{{ root_group }}"
    mode: 0755
  register: rust_fetch

- include_tasks: groovy.yml
  tags: language

- include_tasks: nodejs.yml
  tags: language

- include_tasks: helix.yml

- name: fetch neovim deb
  get_url:
    url: "https://github.com/neovim/neovim/releases/download/v{{ neovim_version }}/nvim-linux64.deb"
    dest: "/tmp/nvim.deb"
    owner: root
    group: "{{ root_group }}"
    mode: 0644

- name: install neovim deb
  apt:
    deb: /tmp/nvim.deb

