- name: install git-delta
  include_role:
    name: packages/binpackages
  vars:
    binpackages_items:
    - name: delta
      version: "{{ git_delta_version }}"
      fetch_url: "https://github.com/dandavison/delta/releases/download/{{ git_delta_version }}/delta-{{ git_delta_version }}-x86_64-unknown-linux-gnu.tar.gz"
      subpath: "delta-{{ git_delta_version }}-x86_64-unknown-linux-gnu"

- name: configure base gitconfig
  blockinfile:
    path: "{{ home_folder }}/.gitconfig"
    block: "{{ lookup('ansible.builtin.template', 'templates/gitconfig.part.j2') }}"

- name: configure git-delta
  template:
    src: "gitconfig-delta.j2"
    dest: "{{ home_folder }}/.gitconfig-delta"
