- name: install git-delta
  include_role:
    name: packages/binpackages
  vars:
    binpackages_items:
    - name: delta
      version: "{{ git_delta_version }}"
      fetch_url: "https://github.com/dandavison/delta/releases/download/{{ git_delta_version }}/delta-{{ git_delta_version }}-{{ alt_arch }}-{{ vendor }}-{{ system }}{{ iflinux_gnu }}.tar.gz"
      subpath: "delta-{{ git_delta_version }}-{{ alt_arch }}-{{ vendor }}-{{ system }}{{ iflinux_gnu }}"

- name: template gitconfig
  become: false
  blockinfile:
    path: "{{ home_folder }}/.gitconfig"
    block: "{{ lookup('ansible.builtin.template', 'templates/gitconfig.part.j2') }}"
