- name: install git-delta
  include_role:
    name: binpackages
  vars:
    binpackages_items:
    - name: delta
      version: "{{ git_delta_version }}"
      fetch_url: "https://github.com/dandavison/delta/releases/download/{{ git_delta_version }}/delta-{{ git_delta_version }}-x86_64-unknown-linux-gnu.tar.gz"
      subpath: "delta-{{ git_delta_version }}-x86_64-unknown-linux-gnu"

- name: ensure git-delta configuration is picked up
  blockinfile:
    path: "{{ home_folder }}/.gitconfig"
    block: |
      [include]
          path = ~/.gitconfig-delta

- name: configure git-delta
  template:
    src: "gitconfig-delta.j2"
    dest: "{{ home_folder }}/.gitconfig-delta"
