---
- name: install lang packages
  become: true
  package:
    name:
    - "golang-go"
    - "python3"
    - "python3-pip"
    - "python3-jedi" #coc.nvim coc-python requirement
    - "julia"
    state: "present"

- import_tasks: rust.yml
  tags: language
- import_tasks: groovy.yml
  tags: language
- import_tasks: nodejs.yml
  tags: language

- import_tasks: helix.yml
- import_tasks: neovim.yml
