---
- name: install lang packages
  become: true
  apt:
    name:
    - "golang-go"
    - "python3"
    - "python3-pip"
    - "python3-jedi" #coc.nvim coc-python requirement
    - "julia"
    state: "present"

- import_tasks: rust.yml
  tags: language
- import_tasks: groovy.yml
  tags: language
- import_tasks: nodejs.yml
  tags: language

- import_tasks: helix.yml
  tags: helix
- name: install neovim
  import_tasks: neovim.yml
- name: install vim
  import_tasks: vim.yml

- name: install non coc-managed lsps
  include_tasks: lsp_external.yml
