---
- include_tasks: "{{ ansible_os_family }}.yml"

- name: install rust
  when: rust_fetch.changed
  become: false
  shell: >
      rustup-init
      --default-toolchain stable
      --default-host {{ alt_arch }}-{{ vendor }}-{{ system}}{{ iflinux_gnu }}
      --profile default
      -y

- name: add rust components
  when: rust_fetch.changed
  become: false
  shell: |
    {{ home_folder }}/.cargo/bin/rustup component add rust-src

- name: install tree-sitter-cli via cargo
  when: ansible_os_family == "Debian"
  become: false
  shell: |
    {{ home_folder }}/.cargo/bin/cargo install tree-sitter-cli
  args:
    creates: "{{ home_folder }}/.cargo/bin/tree-sitter"

- import_tasks: neovim.yml
- import_tasks: git.yml
