- name: ensure the neovim ppa is enabled
  apt_repository:
    repo: "ppa:neovim-ppa/stable"

- name: ensure neovim and lunarvim deps are installed
  apt:
    name:
    - "neovim"
    - "fd-find"
    - "ripgrep"
    state: "present"

- name: install lunarvim python deps with pip
  pip:
    executable: pip3
    name: "pynvim"
    state: "present"

- name: install lunarvim npm modules
  npm:
    name: "{{ item }}"
    global: true
  loop:
  - "neovim"
  - "tree-sitter-cli"

- name: create neovim/lunarvim config directories
  become: false
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
  loop:
  - "{{ home_folder }}/.local/share/lunarvim/lvim"
  - "{{ home_folder }}/.config/lvim"
  - "{{ home_folder }}/.config/nvim"
  - "{{ home_folder }}/.cache/lvim"

- name: ensure lunarvim is cloned
  git:
    repo: "https://github.com/LunarVim/LunarVim.git"
    dest: "{{ home_folder }}/.local/share/lunarvim/lvim"
    update: false
    depth: 1
  notify:
  - lunarvim install

- name: template lunarvim configuration
  become: false
  template:
    src: "lunarvim-config.lua"
    dest: "{{ home_folder }}/.config/lvim/config.lua"
    mode: 0640

- name: template neovim configuration
  become: false
  template:
    src: "init.vim"
    dest: "{{ home_folder }}/.config/nvim/init.vim"
    mode: 0640
