---
- name: ensure neovim dirs are present
  become: false
  file:
    path: "{{ item }}"
    state: directory
  loop:
  - "{{ neovim_autoload_dir }}"
  - "{{ home_folder }}/.config/nvim/lua"

- name: install vimscript configuration
  become: false
  copy:
    src:  "neovim/{{ item }}"
    dest: "{{ home_folder }}/.config/nvim/{{ item }}"
  loop:
  - init.vim
  - theme.vim

- name: install lua configuration
  become: false
  copy:
    src:  "neovim/{{ item }}"
    dest: "{{ home_folder }}/.config/nvim/lua/{{ item }}"
  loop:
  - plugins.lua
  - uiux.lua
  - lsp_configs.lua

- name: set neovim as the default editor
  when: system != "darwin"
  alternatives:
    name: editor
    path: "/usr/bin/nvim"
