---
- name: ensure neovim dirs are present
  become: false
  file:
    path: "{{ item }}"
    state: directory
  loop:
  - "{{ home_folder }}/.config/nvim/lua"
  tags: dots

- name: install vimscript configuration
  become: false
  copy:
    src:  "neovim/{{ item }}"
    dest: "{{ home_folder }}/.config/nvim/{{ item }}"
  loop:
  - init.vim
  - theme.vim
  tags: dots

- name: install lua configuration
  become: false
  copy:
    src:  "neovim/{{ item }}"
    dest: "{{ home_folder }}/.config/nvim/lua/{{ item }}"
  loop:
  - plugins.lua
  - uiux.lua
  - lsp_configs.lua
  tags: dots

- name: set neovim as the default editor
  when: ansible_os_family == "Debian"
  alternatives:
    name: editor
    path: "/usr/bin/nvim"
