- name: fetch rustup-init
  become: true
  get_url:
    url: "https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init"
    dest: "/opt/rustup-init"
    force: false
    owner: root
    group: root
    mode: 0755
  register: vim_rust_fetch

- name: install rust
  when: vim_rust_fetch.changed
  become: false
  shell: >
      /opt/rustup-init
      --default-toolchain stable
      --default-host x86_64-unknown-linux-gnu
      --profile default
      -y

- name: setup nightly, add components
  when: vim_rust_fetch.changed
  become: false
  shell: |
    {{ home_folder }}/.cargo/bin/rustup component add rust-src
