- name: install packages
  package:
    name:
    - "base-devel"
    - "dunst"
    - "zathura"
    - "tree"
    - "curl"
    - "pavucontrol"
    - "gimp"
    - "jq"
    - "ripgrep"
    - "lm_sensors"
    - "htop"
    - "python-openstackclient"
    - "python-virtualenv"
    - "fastfetch"
    - "bitwarden"
    - "bitwarden-cli"
    - "terraform"
    - "packer"
    - "glab"
    - "consul"
    - "consul-template"
    - "nomad"
    - "vault"
    - "zellij"
    - "hugo"
    - "logcli"
    - "kubectl"
    - "cfssl"
    - "talosctl"
    - "fd"
    - "spotify-launcher"
    - "yay"
    state: present
    update_cache: yes

- name: install AUR packages
  become: false
  shell: >
    yay -S --noconfirm --needed
      slack-desktop
      swaylock-effects
      zoom
      levant-bin
      duckdb-bin
      1password-cli
      1password
      grype-bin

- include_tasks: "zathura.yml"
