- name: install packages
  package:
    name:
    - "base-devel"
    - "dunst"
    - "zathura"
    - "tree"
    - "curl"
    - "pavucontrol"
    - "gimp"
    - "jq"
    - "ripgrep"
    - "lm_sensors"
    - "htop"
    - "python-openstackclient"
    - "python-virtualenv"
    - "fastfetch"
    - "bitwarden"
    - "bitwarden-cli"
    - "flatpak"
    - "terraform"
    - "packer"
    - "glab"
    - "consul"
    - "consul-template"
    - "nomad"
    - "vault"
    - "zellij"
    - "hugo"
    - "logcli"
    - "kubectl"
    - "cfssl"
    - "talosctl"
    - "fd"
    state: present
    update_cache: yes

- include_role:
    name: packages/binpackages
  vars:
    binpackages_items:
    - name: fluvio
      version: "{{ fluvio_version }}"
      fetch_url: "https://github.com/infinyon/fluvio/releases/download/v{{ fluvio_version }}/fluvio-x86_64-unknown-linux-musl.zip"
    - name: levant
      version: "{{ levant_version }}"
      fetch_url: "https://releases.hashicorp.com/levant/{{ levant_version }}/levant_{{ levant_version }}_linux_amd64.zip"
    - name: duckdb
      version: "{{ duckdb_version }}"
      fetch_url: "https://github.com/duckdb/duckdb/releases/download/v{{ duckdb_version }}/duckdb_cli-linux-amd64.zip"
    - name: kubelogin
      version: "{{ kubelogin_version }}"
      fetch_url: "https://github.com/int128/kubelogin/releases/download/v{{ kubelogin_version }}/kubelogin_linux_amd64.zip"
      link_name: kubectl-oidc_login
    - name: promql
      version: "{{ promql_cli_version }}"
      fetch_url: "https://github.com/nalbury/promql-cli/releases/download/v{{ promql_cli_version }}/promql-v{{ promql_cli_version }}-linux-amd64.tar.gz"
    - name: 1pass
      version: "{{ onepassword_cli_version }}"
      fetch_url: "https://cache.agilebits.com/dist/1P/op2/pkg/v{{ onepassword_cli_version }}/op_linux_amd64_v{{ onepassword_cli_version }}.zip"
      executable_name: op
    - name: grype
      version: "{{ grype_version }}"
      fetch_url: "https://github.com/anchore/grype/releases/download/v{{ grype_version }}/grype_{{ grype_version }}_linux_amd64.tar.gz"

- include_tasks: "linux.yml"
