- name: install taps
  become: false
  homebrew_tap:
    name: "{{ item }}"
  loop:
  - 1password/tap
  - hashicorp/tap

- name: install packages
  become: false
  homebrew:
    name:
    - "hashicorp/tap/terraform"
    - "hashicorp/tap/packer"
    - "hashicorp/tap/waypoint"
    - "hashicorp/tap/consul"
    - "hashicorp/tap/nomad"
    - "glab"
    - "gh"
    - "consul-template"
    - "hugo"
    - "levant"
    - "octosql"
    - "dagger"
    - "logcli"
    - "tfsec"
    - "kubectl"
    - "tree"
    - "jq"
    - "neofetch"
    - "ripgrep"
    - "htop"
    - "gnu-tar"

- name: install cask packages
  become: false
  homebrew_cask:
    name:
    - "1password"

- name: install non-brew items
  include_role:
    name: packages/binpackages
  vars:
    binpackages_items:
    - name: fluvio
      version: "{{ fluvio_version }}"
      fetch_url: "https://github.com/infinyon/fluvio/releases/download/v{{ fluvio_version }}/fluvio-{{ alt_arch }}-apple-darwin.zip"
