- name: install apt packages
  package:
    name: [
      "build-essential", "dunst", "zathura", "fd-find",
      "tree", "curl", "pavucontrol", "gimp", "jq",
      "ripgrep", "lm-sensors", "htop", "perf-tools-unstable",
      "python3-venv", "python3-openstackclient", "neofetch", "flatpak"
    ]
    state: present
    update_cache: yes

- name: Fetch and install zoom
  become: true
  apt:
    deb: "https://zoom.us/client/{{ zoom_version }}/zoom_amd64.deb"

- name: Fetch bitwarden desktop
  get_url:
    url: "https://github.com/bitwarden/clients/releases/download/desktop-v{{ bitwarden_app_version }}/Bitwarden-{{ bitwarden_app_version }}-amd64.deb"
    dest: "/tmp/bitwarden-v{{ bitwarden_app_version }}.deb"
    owner: root
    group: "{{ root_group }}"
    mode: 0644

- name: Install bitwarden desktop
  become: true
  apt:
    deb: "/tmp/bitwarden-v{{ bitwarden_app_version }}.deb"

- include_tasks: "linux.yml"

- include_role:
    name: packages/binpackages
  vars:
    binpackages_items:
    - name: bw
      version: "{{ bitwarden_cli_version }}"
      fetch_url: "https://github.com/bitwarden/clients/releases/download/cli-v{{ bitwarden_cli_version }}/bw-linux-{{ bitwarden_cli_version }}.zip"
    - name: terraform
      version: "{{ terraform_version }}"
      fetch_url: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
    - name: packer
      version: "{{ packer_version }}"
      fetch_url: "https://releases.hashicorp.com/packer/{{ packer_version }}/packer_{{ packer_version }}_linux_amd64.zip"
    - name: fluvio
      version: "{{ fluvio_version }}"
      fetch_url: "https://github.com/infinyon/fluvio/releases/download/v{{ fluvio_version }}/fluvio-x86_64-unknown-linux-musl.zip"
    - name: glab
      version: "{{ glab_version }}"
      fetch_url: "https://gitlab.com/gitlab-org/cli/-/releases/v{{ glab_version }}/downloads/glab_{{ glab_version }}_Linux_x86_64.tar.gz"
      subpath: "bin"
    - name: consul
      version: "{{ consul_version }}"
      fetch_url: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip"
    - name: nomad
      version: "{{ nomad_version }}"
      fetch_url: "https://releases.hashicorp.com/nomad/{{ nomad_version }}/nomad_{{ nomad_version }}_linux_amd64.zip"
    - name: vault
      version: "{{ vault_version }}"
      fetch_url: "https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{ vault_version }}_linux_amd64.zip"
    - name: consul-template
      version: "{{ consul_template_version }}"
      fetch_url: "https://releases.hashicorp.com/consul-template/{{ consul_template_version }}/consul-template_{{ consul_template_version }}_linux_amd64.zip"
    - name: zellij
      version: "{{ zellij_version }}"
      fetch_url: "https://github.com/zellij-org/zellij/releases/download/v{{ zellij_version }}/zellij-x86_64-unknown-linux-musl.tar.gz"
    - name: hugo
      version: "{{ hugo_version }}"
      fetch_url: "https://github.com/gohugoio/hugo/releases/download/v{{ hugo_version }}/hugo_extended_{{ hugo_version }}_Linux-64bit.tar.gz"
    - name: levant
      version: "{{ levant_version }}"
      fetch_url: "https://releases.hashicorp.com/levant/{{ levant_version }}/levant_{{ levant_version }}_linux_amd64.zip"
    - name: duckdb
      version: "{{ duckdb_version }}"
      fetch_url: "https://github.com/duckdb/duckdb/releases/download/v{{ duckdb_version }}/duckdb_cli-linux-amd64.zip"
    - name: logcli
      version: "{{ logcli_version }}"
      fetch_url: "https://github.com/grafana/loki/releases/download/v{{ logcli_version }}/logcli-linux-amd64.zip"
      executable_name: logcli-linux-amd64
    - name: kubectl
      version: "{{ kubectl_version }}"
      fetch_url: "https://dl.k8s.io/release/v{{ kubectl_version }}/bin/linux/amd64/kubectl"
      archive: false
    - name: talosctl
      version: "{{ talosctl_version }}"
      fetch_url: "https://github.com/siderolabs/talos/releases/download/v{{ talosctl_version }}/talosctl-linux-amd64"
      archive: false
    - name: kubelogin
      version: "{{ kubelogin_version }}"
      fetch_url: "https://github.com/int128/kubelogin/releases/download/v{{ kubelogin_version }}/kubelogin_linux_amd64.zip"
      link_name: kubectl-oidc_login
    - name: promql
      version: "{{ promql_cli_version }}"
      fetch_url: "https://github.com/nalbury/promql-cli/releases/download/v{{ promql_cli_version }}/promql-v{{ promql_cli_version }}-linux-amd64.tar.gz"
    - name: 1pass
      version: "{{ onepassword_cli_version }}"
      fetch_url: "https://cache.agilebits.com/dist/1P/op2/pkg/v{{ onepassword_cli_version }}/op_linux_amd64_v{{ onepassword_cli_version }}.zip"
      executable_name: op
    - name: cfssl
      version: "{{ cfssl_version }}"
      fetch_url: "https://github.com/cloudflare/cfssl/releases/download/v{{ cfssl_version }}/cfssl_{{ cfssl_version }}_linux_amd64"
      archive: false
    - name: cfssljson
      version: "{{ cfssl_version }}"
      fetch_url: "https://github.com/cloudflare/cfssl/releases/download/v{{ cfssl_version }}/cfssljson_{{ cfssl_version }}_linux_amd64"
      archive: false
    - name: grype
      version: "{{ grype_version }}"
      fetch_url: "https://github.com/anchore/grype/releases/download/v{{ grype_version }}/grype_{{ grype_version }}_linux_amd64.tar.gz"
