- name: install apt packages
  package:
    name: [
      "build-essential", "chromium-browser", "dunst", "zathura",
      "tree", "curl", "pavucontrol", "gimp", "jq",
      "ripgrep", "lm-sensors", "htop", "perf-tools-unstable",
      "python3-openstackclient", "neofetch"
    ]
    state: present
    update_cache: yes

- include_tasks: package.yml
  loop: "{{ binpackages_items | list }}"

- name: template configuration
  become: false
  template:
    dest: "{{ home_folder }}/.{{ item }}"
    src: "templates/{{ item }}.j2"
  loop: [ "config/zathura/zathurarc" ]
  tags: theme

- name: install flatpak packages
  become: false
  flatpak:
    name: "{{ item }}"
    method: "user"
    state: present
  loop:
  - "com.slack.Slack"
  - "us.zoom.Zoom"
  - "com.spotify.Client"

- name: Fetch bitwarden desktop
  get_url:
    url: "https://github.com/bitwarden/clients/releases/download/desktop-v{{ bitwarden_app_version }}/Bitwarden-{{ bitwarden_app_version }}-amd64.deb"
    dest: "/tmp/bitwarden-v{{ bitwarden_app_version }}.deb"
    owner: root
    group: root
    mode: 0644

- name: Install bitwarden desktop
  become: true
  apt:
    deb: "/tmp/bitwarden-v{{ bitwarden_app_version }}.deb"
