- name: install apt packages
  apt:
    name: [
      "build-essential", "chromium-browser", "alpine", "dunst",
      "zathura", "tree", "screen", "curl", "pavucontrol", "gimp",
      "jq", "ripgrep", "lm-sensors", "htop", "perf-tools-unstable",
      "pssh", "python3-openstackclient"
    ]
    state: present
    update_cache: yes

- name: install flatpak packages
  become: false
  flatpak:
    name: "com.slack.Slack"
    method: "user"
    state: present

- name: set file configuration
  become: false
  copy:
    dest: "{{ home_folder }}/.{{ item }}"
    src:  "files/{{ item }}"
  loop:
  - "bash_aliases"
  - "screenrc"
  - "inputrc"
  - "pinerc"

- name: template configuration
  become: false
  template:
    dest: "{{ home_folder }}/.{{ item }}"
    src: "templates/{{ item }}"
  loop:
  - "bashrc"

- name: set directory configuration
  become: false
  copy:
    dest: "{{ home_folder }}/.config/"
    src:  "files/config/{{ item }}"
  with_items:
  - "dunst"
  - "zathura"

- name: link parallel-ssh to pssh
  become: true
  file:
    path: "/usr/bin/pssh"
    src: "/usr/bin/parallel-ssh"
    state: "link"
    owner: root
    group: root
    mode: 0755
