- name: install apt packages
  apt:
    name: [
      "build-essential", "chromium-browser", "dunst", "zathura",
      "tree", "curl", "pavucontrol", "gimp", "jq",
      "ripgrep", "lm-sensors", "htop", "perf-tools-unstable",
      "pssh", "python3-openstackclient", "neofetch"
    ]
    state: present
    update_cache: yes

- name: install flatpak packages
  become: false
  flatpak:
    name: "{{ item }}"
    method: "user"
    state: present
  loop:
  - "com.slack.Slack"
  - "us.zoom.Zoom"
  - "com.spotify.Client"

- name: template configuration
  become: false
  template:
    dest: "{{ home_folder }}/.{{ item }}"
    src: "templates/{{ item }}.j2"
  loop: [ "config/zathura/zathurarc" ]
  tags: theme

- name: link parallel-ssh to pssh
  become: true
  file:
    path: "/usr/bin/pssh"
    src: "/usr/bin/parallel-ssh"
    state: "link"
    owner: root
    group: root
    mode: 0755
