export JAVA_HOME=/usr/lib/jvm/java-8-oracle/jre/

alias git-log='git log --oneline --decorate --graph --all'
alias trc='transmission-remote-cli'
alias cgrep='grep --color=always'
alias grep='grep --color=auto'
alias diff='diff --color'
alias less='less -R'
alias screendev='screen -c ~/.screendevrc'
alias vimd='vim -u ~/.vimdevrc'
alias ncmpcphome='ncmpcpp -c ~/.ncmpcpp/config_server'
alias ls='ls --literal --color=auto'
alias lk='ls --color=never'
alias info='info --vi-keys'

alias kubeprod='kubectl --context production'
alias kubestage='kubectl --context staging'
alias kubeshared='kubectl --context shared'

alias myip='dig @resolver1.opendns.com myip.opendns.com +short'
