terraform_version: "1.0.8"
packer_version: "1.7.6"
fluvio_version: "0.9.9"
glab_version: "1.25.3"
consul_version: "1.10.4"
nomad_version: "1.2.2"
consul_template_version: "0.27.2"
zellij_version: "0.23.0"
hugo_version: "0.92.1"
levant_version: "0.3.1"
duckdb_version: "1.0.0"
logcli_version: "2.6.1"
kubectl_version: "1.26.0"
talosctl_version: "1.8.0"
promql_cli_version: "0.3.0"
onepassword_cli_version: "2.14.0"
bitwarden_app_version: "2023.3.1"
bitwarden_cli_version: "2023.3.0"
cfssl_version: "1.6.4"
grype_version: "0.82.0"
kubelogin_version: "1.31.0"
