#!/bin/bash

hc() {
    herbstclient "$@"
}

# color_accent='#C6892E'
# color_bg='#262626'
# dmenu_accent="$color_accent"

color_accent='#94C0E3'
color_bg='#262626'
color_urgent='#718475'
dmenu_accent="$color_accent"

#xrandr monitors
#xrandr --output eDP1 --auto
#xrandr --output HDMI1 --auto --left-of eDP1

#startup applications
setxkbmap us
# wmname LG3D
compton -c -C -r 5 -l -8 -t -8 -m 0.95 -G -D 15 --backend glx --paint-on-overlay --glx-no-stencil --vsync opengl-swc &
if [[ `pidof syndaemon` -ne 0 ]]; then
    killall syndaemon
fi
syndaemon -i 1 -d
mpd
nitrogen --restore
~/scripts/hhpc.sh



hc emit_hook reload

# set keyboard repeat-key-when-pressed delay to 250ms, repeat to 30 keystrokes per second.
xset r rate 350 30

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-Return spawn urxvtcd

# Launcher
# hc keybind $Mod-d spawn dmenu_run -fn -*-terminus-medium-r-normal-*-14-*-*-*-*-*-* -nb "$color_bg" -nf "$dmenu_accent" -sb "$dmenu_accent" -sf "$color_bg"
hc keybind $Mod-d spawn dmenu_run -fn "Deja Vu Sans Mono-10:book:pixelsize=13:antialias=true:hinting=true" -nb "$color_bg" -nf "$dmenu_accent" -sb "$dmenu_accent" -sf "$color_bg"

# Screenshot
hc keybind Print spawn scrot 

# Keyboard locale
# hc keybind $Mod-bracketleft    spawn setxkbmap us
# hc keybind $Mod-bracketright   spawn setxkbmap gr
setxkbmap -option grp:win_space_toggle us,el

# Sound
hc keybind XF86AudioRaiseVolume spawn amixer -D pulse sset Master 5%+
hc keybind XF86AudioLowerVolume spawn amixer -D pulse sset Master 5%-
hc keybind XF86AudioMute spawn amixer -D pulse sset Master 1+ toggle

hc keybind $Mod-equal spawn amixer -D pulse sset Master 5%+
hc keybind $Mod-minus spawn amixer -D pulse sset Master 5%-

# Brightness
hc keybind XF86MonBrightnessUp spawn xbacklight -inc 10
hc keybind XF86MonBrightnessDown spawn xbacklight -dec 10

# basic movement
# focusing clients
# hc keybind $Mod-Left  focus left
# hc keybind $Mod-Down  focus down
# hc keybind $Mod-Up    focus up
# hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.025
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

hc keybind $Mod-w            set_attr theme.active.color $color_accent
hc keybind $Mod-Shift-w      set_attr theme.active.color $color_bg


# tags
#tag_names=( {1..9} )
tag_names=( '!' '@' '#' '$' '%' '&' )
#tag_keys=( ampersand eacute quotedbl apostrophe parenleft section egrave exclam ccedilla 0 )
tag_keys=( {1..6} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-Shift-space cycle_layout 1
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_width 0
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_normal_opacity 0
hc set frame_active_opacity 0
hc set frame_transparent_width 0
hc set frame_padding 0
hc set frame_gap 16

hc set window_gap 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 0
hc set mouse_recenter_gap 0
hc set default_frame_layout 2

hc attr theme.active.color $color_accent
hc attr theme.normal.color $color_bg
hc attr theme.urgent.color $color_urgent
hc attr theme.inner_width 1
hc attr theme.inner_color $color_bg
hc attr theme.border_width 4
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color $color_bg
hc attr theme.active.inner_color $color_bg
hc attr theme.active.outer_color $color_bg
hc attr theme.background_color $color_bg

# rules
hc unrule -F
hc rule focus=on # normally focus new clients
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
hc detect_monitors

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" $monitor &
done
