- name: install packages
  become: false
  homebrew:
    name:
    - "hammerspoon"

- name: install casks
  become: false
  homebrew_cask:
    name:
    - "karabiner-elements"

- name: ensure configuration directories exist
  become: false
  file:
    path: "{{ home_folder }}/{{ item }}"
    state: "directory"
  loop:
  - .config/karabiner
  - .hammerspoon
  tags: dots

- name: set karabiner remappings
  become: false
  copy:
    remote_src: false
    src: "karabiner/karabiner.json"
    dest: "{{ home_folder }}/.config/karabiner/karabiner.json"
  tags: dots


- name: clone hammerspoon spoons
  become: false
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ home_folder }}/.hammerspoon/Spoons/{{ item.spoon }}"
    version: main
  loop:
  - repo: git@github.com:mogenson/PaperWM.spoon.git
    spoon: PaperWM.spoon
  - repo: git@github.com:mogenson/WarpMouse.spoon.git
    spoon: WarpMouse.spoon
  tags: dots

- name: configure hammerspoon/paperwm
  become: false
  copy:
    remote_src: false
    src: "hammerspoon/{{ item }}"
    dest: "{{ home_folder }}/.hammerspoon/{{ item }}"
  loop:
  - init.lua
  - paperwm_hotkeys.lua
#  notify: hammerspoon reload
  tags: dots
