- name: add yabai tap
  become: false
  homebrew_tap:
    name: "{{ item }}"
  loop:
  - "koekeishiya/formulae"
  - "FelixKratz/formulae"

- name: install packages
  become: false
  homebrew:
    name:
    - "koekeishiya/formulae/yabai"
    - "koekeishiya/formulae/skhd"
  notify: restart skhd

- name: install casks
  become: false
  homebrew_cask:
    name:
    - "karabiner-elements"

- name: ensure configuration directories exist
  become: false
  file:
    path: "{{ home_folder }}/.config/{{ item }}"
    state: "directory"
  loop:
  - karabiner
  tags: dots

- name: set karabiner remappings
  become: false
  copy:
    remote_src: false
    src: "karabiner/karabiner.json"
    dest: "{{ home_folder }}/.config/karabiner/karabiner.json"
  tags: dots

- name: configure skhd
  become: false
  template:
    src: "skhdrc.j2"
    dest: "{{ home_folder }}/.skhdrc"
  tags: dots

- name: configure yabai
  become: false
  template:
    src: "yabairc.j2"
    dest: "{{ home_folder }}/.yabairc"
  notify: restart yabai
  tags: dots
