- name: restart pipewire
  become: false
  systemd_service:
    scope: user
    name: pipewire
    state: restarted
  when: skip_handlers is not defined or skip_handlers is false
    
- name: restart wireplumber
  become: false
  systemd_service:
    scope: user
    name: wireplumber
    state: restarted
  when: skip_handlers is not defined or skip_handlers is false
