---
- name: install package
  become: true
  apt:
    name: "vim-gtk3"
    state: "present"

- name: add configuration for terminal programs
  become: false
  copy:
    src:  "{{ item }}"
    dest: "{{ home_folder }}/.{{ item }}"
  with_items:
  - "vimrc"

- name: ensure the vim autoload directory exists
  become: false
  file:
    path: "{{ home_folder }}/.vim/autoload"
    state: "directory"
    mode: 0755

- name: install vim-plug
  become: false
  get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "{{ home_folder }}/.vim/autoload/plug.vim"

- name: install vim plugins
  shell: >
    vim +PlugInstall +qall

- import_tasks: rust.yml
- import_tasks: go.yml
- import_tasks: python.yml
- import_tasks: groovy.yml
