---
- name: install vim and lang packages
  become: true
  apt:
    name:
    - "vim-gtk3"
    - "golang-go"
    - "nodejs"
    - "npm"
    - "python3"
    - "python3-pip"
    state: "present"

- import_tasks: rust.yml
- import_tasks: groovy.yml

- name: install configuration for vim
  become: false
  copy:
    src:  "{{ item }}"
    dest: "{{ home_folder }}/.{{ item }}"
  loop: [ "vimrc", "vimpluginrc" ]

- name: ensure the vim autoload directory exists
  become: false
  file:
    path: "{{ home_folder }}/.vim/autoload"
    state: "directory"
    mode: 0755

- name: install vim-plug
  become: false
  get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "{{ home_folder }}/.vim/autoload/plug.vim"

- name: install vim plugins via vim-plug
  shell: >
    vim +PlugInstall +qall
