---
- name: install package
  become: true
  apt:
    name: "vim-gtk3"
    state: "present"

- name: add configuration for terminal programs
  become: false
  copy:
    src:  "{{ item }}"
    dest: "{{ home_folder }}/.{{ item }}"
  with_items:
  - "vimrc"

- name: install vundle
  become: false
  git:
    repo: "https://github.com/VundleVim/Vundle.vim.git"
    dest: "{{ home_folder }}/.vim/bundle/Vundle.vim"
    depth: 1

- import_tasks: rust.yml
- import_tasks: go.yml
- import_tasks: python.yml
- import_tasks: groovy.yml
