- name: fetch rustup-init
  become: true
  get_url:
    url: "https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init"
    dest: "/opt/rustup-init"
    force: false
    owner: root
    group: root
    mode: 0755
  register: vim_rust_fetch

- name: install rust
  when: vim_rust_fetch.changed
  become: false
  shell: >
      /opt/rustup-init
      --default-toolchain stable
      --default-host x86_64-unknown-linux-gnu
      --profile default
      -y

- name: setup nightly, add components
  when: vim_rust_fetch.changed
  become: false
  shell: |
    {{ home_folder }}/.cargo/bin/rustup component add rust-src

- name: check if rust-analyzer is already present
  file:
    path: "{{ home_folder }}/.local/bin/rust-analyzer"
    state: "file"
  ignore_errors: true
  register: vim_rust_analyzer_installed

- name: fetch latest rust-analyzer
  become: false
  when: vim_rust_analyzer_installed.failed or force_install_rust_analyzer
  shell: |
    curl -Ls https://github.com/rust-analyzer/rust-analyzer/releases/latest/download/rust-analyzer-x86_64-unknown-linux-gnu.gz -o- | gunzip -c - > ~/.local/bin/rust-analyzer
    chmod +x ~/.local/bin/rust-analyzer
  args:
    warn: false
