---
- name: ensure icons directory exists
  become: true
  file:
    path: "{{ cursors_dir }}"
    state: directory

- name: fetch and extract bibata archive
  become: true
  unarchive:
    remote_src: true
    src: "https://github.com/ful1e5/Bibata_Cursor/releases/download/{{ bibata_version }}/Bibata.tar.gz"
    dest: "{{ cursors_dir }}"
    creates: "{{ cursors_dir }}/Bibata-Original-Classic"
    owner: root
    group: root
