---
- name: install polybar package
  package:
    name: [ "polybar" ]
    state: present
  ignore_errors: true
  register: polybar_package_present

- name: fallback to source-install
  import_tasks: fromsource.yml
  when:
  - polybar_package_present.failed

- name: ensure Noto Color Emoji font is installed
  package:
    name: "{{ polybar_noto_color_emoji_font_package }}"
    state: present

- name: Set fact all network interfaces
  set_fact:
    ether_ifaces: "{{ ansible_facts.interfaces | map('regex_replace', '-', '_') | map('extract', ansible_facts ) | selectattr('type', 'equalto', 'ether') | sort(attribute='device') }}"
  tags: theme

- name: Get wifi network interfaces
  set_fact:
    wifi_ifaces: "{{ ether_ifaces | selectattr('device', 'match', 'w.*') }}"
  tags: theme

- name: Set fact wired network interfaces
  set_fact:
    wired_ifaces: "{{ ether_ifaces | selectattr('device', 'match', 'e.*') }}"
  tags: theme

- name: ensure polybar config directory exists
  become: false
  file:
    path: "{{ home_folder }}/.config/polybar"
    state: directory

- name: template polybar configuration
  become: false
  template:
    src: "config"
    dest: "{{ home_folder }}/.config/polybar/config"
  tags:
  - theme

- name: copy herbstluft-polybar-panel configuration
  become: false
  copy:
    src: "panel.sh"
    dest: "{{ home_folder }}/.config/polybar/panel.sh"
    mode: 0755
