---
- name: install polybar package
  apt:
    name: [ "polybar={{ polybar_version }}*" ]
    state: present
  ignore_errors: true
  register: polybar_package_present

- name: fallback to source-install
  include: fromsource.yml
  when:
  - polybar_package_present.failed

- name: ensure polybar config directory exists
  become: false
  file:
    path: "{{ home_folder }}/.config/polybar"
    state: directory

- name: template polybar configuration
  become: false
  template:
    src: "config"
    dest: "{{ home_folder }}/.config/polybar/config"
  tags:
  - theme

- name: copy herbstluft-polybar-panel configuration
  become: false
  copy:
    src: "panel.sh"
    dest: "{{ home_folder }}/.config/polybar/panel.sh"
    mode: 0755
