home_folder: "/home/{{ ansible_env.SUDO_USER }}"
global_font: "Fira Code Nerd Font"
bitwarden_app_version: "2023.1.1"
bitwarden_cli_version: "1.22.1"
terraform_version: "1.4.2"
packer_version: "1.8.5"
waypoint_version: "0.10.5"
fluvio_version: "0.10.4"
glab_version: "1.25.3"
starship_version: "1.12.0"
consul_version: "1.14.4"
nomad_version: "1.4.3"
zellij_version: "0.23.0"
hugo_version: "0.92.1"
levant_version: "0.3.1"
octosql_version: "0.12.0"
dagger_version: "0.3.10"
logcli_version: "2.6.1"
tfsec_version: "1.28.1"
zoxide_version: "0.9.0"
fzf_version: "0.38.0"
helix_version: "22.12"
terraform_ls_version: "0.30.3"
kubectl_version: "1.26.0"
