real_arch: "{% if ansible_architecture == 'x86_64' %}amd64{% else %}arm64{% endif %}"
alt_arch: "{% if ansible_architecture == 'x86_64' %}x86_64{% else %}aarch64{% endif %}"
system: "{{ ansible_system | lower }}"
vendor: "{% if system == 'darwin' %}apple{% else %}unknown{% endif %}"
iflinux_musl: "{% if system == 'linux' %}-musl{% endif %}"
iflinux_gnu: "{% if system == 'linux' %}-gnu{% endif %}"
home_folder: "{% if system == 'darwin' %}/Users/{% else %}/home/{% endif %}{{ ansible_env.SUDO_USER }}"
package_manager_become: "{{ (system != 'darwin') | bool }}"
root_group: "{% if system == 'darwin' %}wheel{% else %}root{% endif %}"

bitwarden_app_version: "2024.5.0"
bitwarden_cli_version: "2024.4.1"
terraform_version: "1.9.2"
packer_version: "1.11.1"
fluvio_version: "0.11.9"
glab_version: "1.43.0"
starship_version: "1.19.0"
consul_version: "1.19.1"
nomad_version: "1.8.2"
vault_version: "1.17.2"
zellij_version: "0.40.1"
hugo_version: "0.111.3"
levant_version: "0.3.2"
duckdb_version: "1.0.0"
logcli_version: "3.1.0"
zoxide_version: "0.9.4"
fzf_version: "0.53.0"
helix_version: "24.03"
kubectl_version: "1.30.0"
neovim_bob_version: "2.9.1"
neovim_version: "0.10.1"
promql_cli_version: "0.3.0"
onepassword_cli_version: "2.29.0"
consul_template_version: "0.39.0"
cfssl_version: "1.6.5"
