home_folder: "/home/{{ ansible_env.SUDO_USER }}"
global_font: "Fira Code Nerd Font"
bitwarden_app_version: "2023.3.1"
bitwarden_cli_version: "2023.3.0"
terraform_version: "1.4.5"
packer_version: "1.8.6"
waypoint_version: "0.11.0"
fluvio_version: "0.10.6"
glab_version: "1.27.0"
starship_version: "1.12.0"
consul_version: "1.15.2"
nomad_version: "1.5.2"
zellij_version: "0.35.2"
hugo_version: "0.111.3"
levant_version: "0.3.2"
octosql_version: "0.12.1"
dagger_version: "0.4.1"
logcli_version: "2.7.4"
tfsec_version: "1.28.1"
zoxide_version: "0.9.0"
fzf_version: "0.38.0"
helix_version: "22.12"
terraform_ls_version: "0.30.3"
kubectl_version: "1.26.0"
neovim_version: "0.8.3"
promql_cli_version: "0.3.0"
onepassword_cli_version: "2.14.0"
