home_folder: "/home/{{ ansible_env.SUDO_USER }}"
global_font: "Fira Code Nerd Font"
bitwarden_app_version: "2022.6.1"
bitwarden_cli_version: "1.22.1"
terraform_version: "1.3.1"
packer_version: "1.8.3"
waypoint_version: "0.10.2"
fluvio_version: "0.9.33"
glab_version: "1.22.0"
starship_version: "1.10.3"
consul_version: "1.13.3"
nomad_version: "1.4.2"
zellij_version: "0.23.0"
hugo_version: "0.92.1"
levant_version: "0.3.1"
octosql_version: "0.12.0"
dagger_version: "0.2.36"
logcli_version: "2.6.1"
