real_arch: "{% if ansible_architecture == 'x86_64' %}amd64{% else %}arm64{% endif %}"
alt_arch: "{% if ansible_architecture == 'x86_64' %}x86_64{% else %}aarch64{% endif %}"
system: "{{ ansible_system | lower }}"
vendor: "{% if system == 'darwin' %}apple{% else %}unknown{% endif %}"
iflinux_musl: "{% if system == 'linux' %}-musl{% endif %}"
iflinux_gnu: "{% if system == 'linux' %}-gnu{% endif %}"
home_folder: "{% if system == 'darwin' %}/Users/{% else %}/home/{% endif %}{{ ansible_env.SUDO_USER }}"
package_manager_become: "{{ (system != 'darwin') | bool }}"
root_group: "{% if system == 'darwin' %}wheel{% else %}root{% endif %}"

bitwarden_app_version: "2024.5.0"
bitwarden_cli_version: "2024.4.1"
terraform_version: "1.8.4"
packer_version: "1.10.3"
fluvio_version: "0.11.8"
glab_version: "1.40.0"
starship_version: "1.19.0"
consul_version: "1.18.2"
nomad_version: "1.7.7"
vault_version: "1.16.2"
zellij_version: "0.35.2"
hugo_version: "0.111.3"
levant_version: "0.3.2"
octosql_version: "0.12.2"
logcli_version: "2.8.6"
zoxide_version: "0.9.4"
fzf_version: "0.52.1"
helix_version: "24.03"
kubectl_version: "1.30.0"
neovim_bob_version: "2.9.1"
neovim_version: "0.10.0"
promql_cli_version: "0.3.0"
onepassword_cli_version: "2.21.0"
consul_template_version: "0.34.0"
cfssl_version: "1.6.4"
