real_arch: "{% if ansible_architecture == 'x86_64' %}amd64{% else %}arm64{% endif %}"
alt_arch: "{% if ansible_architecture == 'x86_64' %}x86_64{% else %}aarch64{% endif %}"
system: "{{ ansible_system | lower }}"
vendor: "{% if system == 'darwin' %}apple{% else %}unknown{% endif %}"
iflinux_musl: "{% if system == 'linux' %}-musl{% endif %}"
iflinux_gnu: "{% if system == 'linux' %}-gnu{% endif %}"
home_folder: "{% if system == 'darwin' %}/Users/{% else %}/home/{% endif %}{{ ansible_env.SUDO_USER }}"
package_manager_become: "{{ (system != 'darwin') | bool }}"
root_group: "{% if system == 'darwin' %}wheel{% else %}root{% endif %}"

bitwarden_app_version: "2024.11.1"
bitwarden_cli_version: "2024.11.0"
terraform_version: "1.10.0"
packer_version: "1.11.2"
fluvio_version: "0.12.0"
glab_version: "1.46.1"
starship_version: "1.21.1"
consul_version: "1.20.0"
nomad_version: "1.9.3"
vault_version: "1.18.1"
zellij_version: "0.40.1"
hugo_version: "0.134.3"
levant_version: "0.3.2"
duckdb_version: "1.1.3"
logcli_version: "3.2.1"
zoxide_version: "0.9.6"
fzf_version: "0.55.0"
helix_version: "24.07"
kubectl_version: "1.31.0"
neovim_bob_version: "2.9.1"
neovim_version: "0.10.2"
promql_cli_version: "0.3.0"
onepassword_cli_version: "2.29.0"
consul_template_version: "0.39.0"
cfssl_version: "1.6.5"
picom_fromsource_version: "12.5"
python_uv_version: "0.5.4"
talosctl_version: "1.8.1"
grype_version: "0.84.0"
kubelogin_version: "1.31.0"
