- name: Fetch bitwarden desktop
  get_url: 
    url: "https://github.com/bitwarden/desktop/releases/download/v{{ bitwarden_app_version }}/Bitwarden-{{ bitwarden_app_version }}-amd64.deb"
    dest: "/tmp/bitwarden-v{{ bitwarden_app_version }}.deb"
    owner: root
    group: root
    mode: 0644

- name: Install bitwarden desktop
  become: true
  apt:
    deb: "/tmp/bitwarden-v{{ bitwarden_app_version }}.deb"

- name: Ensure bwcli directory exists
  become: true
  file:
    path: "/opt/bitwarden/"
    state: "directory"
    owner: root
    group: root
    mode: 0755

- name: Verify current cli version is installed
  become: true
  file:
    path: "/opt/bitwarden/bw-{{ bitwarden_cli_version }}"
    state: "file"
    owner: root
    group: root
    mode: 0755
  ignore_errors: true
  register: verify

- name: Fetch bitwarden cli
  become: true
  get_url: 
    url: "https://github.com/bitwarden/cli/releases/download/v{{ bitwarden_cli_version }}/bw-linux-{{ bitwarden_cli_version }}.zip"
    dest: "/tmp/bwcli.zip"
    owner: root
    group: root
    mode: 0644
  when: verify.failed

- name: Unarchive bitwarden cli
  become: true
  unarchive:
    remote_src: true
    src: "/tmp/bwcli.zip"
    dest: "/opt/bitwarden/"
  when: verify.failed

- name: Copy to versioned naming
  become: true
  copy:
    remote_src: true
    src: "/opt/bitwarden/bw"
    dest: "/opt/bitwarden/bw-{{ bitwarden_cli_version }}"
    owner: root
    group: root
    mode: 0755
  when: verify.failed

- name: Ensure extracted executable is absent
  file:
    path: "/opt/bitwarden/bw"
    state: "absent"

- name: Link versioned executable to active
  file:
    path: "/usr/local/bin/bw"
    src: "/opt/bitwarden/bw-{{ bitwarden_cli_version }}"
    state: "link"
