---
- name: install fira code package
  apt:
    name: "fonts-firacode"
    state: present
  ignore_errors: true
  register: firacode_package_present

- name: fallback to source-install
  include: fromsource.yml
  when:
  - firacode_package_present.failed

