- name: Configure arch desktop
  hosts: localhost
  tasks:
      - name: update AUR
        command: yaourt -Sy

      - name: install AUR packages
        command: yaourt -S urxvtcd alpine --noconfirm --needed

      - name: config mail addressbook
        file: >
            dest=/home/efthymiosh/.addressbook
            src=/home/efthymiosh/.rice/.addressbook
            state=link

      - name: config alpine
        file: >
            dest=/home/efthymiosh/.pinerc
            src=/home/efthymiosh/.rice/.pinerc
            state=link
