- name: install packages
  apt:
    name: rxvt-unicode
    state: latest

- name: template {{ item.dest }}
  become: false
  template:
    src: "{{ item.template }}"
    dest: "{{ home_folder }}/{{ item.dest }}"
  with_items:
  - template: "Xdefaults.j2"
    dest: ".Xdefaults"
  - template: "Xresources.j2"
    dest: ".Xresources"
  tags:
  - theme
