---
- name: install ppa repository
  become: true
  apt_repository:
    repo: "ppa:jonathonf/vim"

- name: install package
  become: true
  apt:
    name: "vim-gtk3"
    state: "present"

- name: add configuration for terminal programs
  become: false
  copy:
    src:  "{{ item }}"
    dest: "{{ home_folder }}/.{{ item }}"
  with_items:
  - "vimrc"
  - "vimdevrc"

- name: install vundle
  become: false
  git:
    repo: "https://github.com/VundleVim/Vundle.vim.git"
    dest: "{{ home_folder }}/.vim/bundle/Vundle.vim"
    depth: 1
