- name: ensure pipewire.conf.d exists
  become: true
  file:
    path: "/usr/share/pipewire/pipewire.conf.d"
    state: directory

- name: copy pipewire user overrides
  become: true
  copy:
    remote_src: false
    src: pipewire.conf
    dest: "/usr/share/pipewire/pipewire.conf.d/bluez.conf"
  notify:
  - restart wireplumber
  - restart pipewire

- name: template faillock configuration
  become: true
  template:
    src: faillock.conf
    dest: /etc/security/faillock.conf
