---
polybar_fromsource_version: "3.5.4"
polybar_temp_dir: "/tmp"
polybar_noto_color_emoji_font_package: "{% if ansible_os_family == 'Debian' %}fonts-noto-color-emoji{% else %}noto-fonts-emoji{% endif %}"
polybar_thermal_zone: "6"

home_folder: "/home/{{ ansible_env.SUDO_USER }}"

theme:
  background: '202020'
  foreground: 'c5c8c6'
  bright:
    black: '3f3f3f'
    yellow: 'f0c675'
    cyan: '5e8d87'
    red: 'cc6666'
  normal:
    black: '282a2e'
    red: 'a54242'
    green: '8c9440'
    yellow: 'de935f'
    blue: '5f819d'
    magenta: '85678f'
    cyan: '5e8d87'
    white: '707880'
  accent: 'e60053'
