- name: Configure arch desktop
  hosts: localhost
  become: true

  vars_files:
  - "./vars/themes/dark/catpuccin_mochaer.yml"
  - "./vars/common.yml"

  vars:
    x_cursor_size: "32"
    x_cursor_theme: "Bibata-Modern-Catpuccin-Mocha-Rosewater-Inverse"
    niri_wallpaper: "Pictures/wallpapers/firewatch-dark-minimal-5k-5120x2880-MOCHA.jpeg"
    global_font: "FiraCode Nerd Font"
    alacritty_font_size: "{{ global_font_size }}"
    skip_handlers: true

  roles:
  - role: development
    tags: development
  - role: terminal
    tags: terminal
  - role: desktop/wayland
    tags: wayland
  - role: apps/firefox
    tags: firefox
