- name: Configure macos desktop
  hosts: localhost
  become: true

  vars_files:
  - "vars/themes/dark/tokyonight_midnight.yml"
  - "vars/common.yml"

  vars:
    provision_hostname: "pattiha"
    global_font: "FiraCode Nerd Font"
    alacritty_font_size: "{{ global_font_size }}"

  roles:
  - role: packages
    tags: packages
  - role: fonts
    tags: fonts
  - role: terminal
    tags: terminal
  - role: development
    tags: development
  - role: desktop/mac
    tags: desktop
  - role: apps
    tags: apps

  tasks:
  - name: modify hostname
    become: true
    hostname:
      name: "{{ provision_hostname }}"
