- name: Configure macos desktop
  hosts: localhost
  become: false

  vars_files:
  - "vars/themes/dark/tokyonight_night.yml"
  - "vars/common.yml"

  vars:
    provision_hostname: "patticha"

  roles:
  - role: packages
    tags: packages
  - role: terminal
    tags: terminal

  tasks:
  - name: modify hostname
    become: true
    hostname:
      name: "{{ provision_hostname }}"
