- name: Configure ubuntu desktop
  hosts: localhost
  become: true

  vars_files:
  - "files/themes/dark/termsexy_gray.yml"

  vars:
    home_folder: "/home/{{ ansible_env.SUDO_USER }}"
    rice_location: "{{ home_folder }}/cloned/rice"
    polybar_version: "3.5.4"
    polybar_thermal_zone: "6"
    x_cursor_theme: "Pop"
    x_cursor_size: "24"
    alacritty_version: "0.9.0"

  roles:
  - role: fira-code
    tags: fira-code
  - role: vim
    tags: vim
  - role: alacritty
    tags: alacritty
  - role: rofi
    tags: rofi
  - role: cursors
    tags: cursors
  - role: xdefaults
    tags: xdefaults
  - role: herbstluftwm
    tags: herbstluftwm
  - role: polybar
    tags: polybar

  pre_tasks:
  - name: update apt package information
    apt:
      update_cache: yes

  tasks:
  - name: install packages
    apt:
      name: [
        "build-essential", "chromium-browser", "alpine", "dunst",
        "zathura", "tree", "screen", "curl", "pavucontrol", "gimp",
        "jq", "ripgrep", "lm-sensors"
      ]
      state: present
      update_cache: no

  - name: set file configuration
    become: false
    copy:
      dest: "{{ home_folder }}/.{{ item }}"
      src:  "files/{{ item }}"
    with_items:
    - "bashrc"
    - "bash_aliases"
    - "screenrc"
    - "inputrc"
    - "pinerc"

  - name: set directory configuration
    become: false
    copy:
      dest: "{{ home_folder }}/.config/"
      src:  "files/config/{{ item }}"
    with_items:
    - "dunst"
    - "zathura"
