- name: Configure arch desktop
  hosts: localhost
  become: True
  tasks:
      - name: config bashrc
        file: >
            dest=/home/efthymiosh/.bashrc
            src=/home/efthymiosh/.rice/.bashrc
            state=link

      - name: config screenrc
        file: >
            dest=/home/efthymiosh/.screenrc
            src=/home/efthymiosh/.rice/.screenrc
            state=link

      - name: config inputrc
        file: >
            dest=/home/efthymiosh/.inputrc
            src=/home/efthymiosh/.rice/.inputrc
            state=link

      - name: config bash aliases
        file: >
            dest=/home/efthymiosh/.bash_aliases
            src=/home/efthymiosh/.rice/.bash_aliases
            state=link

      - name: install nitrogen
        pacman: name=nitrogen

      - name: install dunst
        pacman: name=dunst

      - name: link dunst config folder
        file: >
            dest=/home/efthymiosh/.config/dunst
            src=/home/efthymiosh/.rice/.config/dunst
            state=link

      - name: install zathura
        pacman: name=zathura

      - name: link zathura config folder
        file: >
            dest=/home/efthymiosh/.config/zathura
            src=/home/efthymiosh/.rice/.config/zathura
            state=link

      - name: install compton
        pacman: name=compton

      - name: install rxvt-unicode
        pacman: name=rxvt-unicode

      - name: config .Xdefaults
        command: cpp /home/efthymiosh/.rice/.Xdefaults -P -o ~/.Xdefaults 

      - name: install sxiv
        pacman: name=sxiv

      - name: install vim
        pacman: name=vim

      - name: link vimrc
        file: >
            dest=/home/efthymiosh/.vimrc
            src=/home/efthymiosh/.rice/.vimrc
            state=link

      - name: link vimdevrc
        file: >
            dest=/home/efthymiosh/.vimdevrc
            src=/home/efthymiosh/.rice/.vimdevrc
            state=link

      - name: install git
        pacman: name=git

      - name: install xf86-input-synaptics
        pacman: name=xf86-input-synaptics

      - name: install bash-completion
        pacman: name=bash-completion

      - name: install mpd
        pacman: name=mpd

      - name: config mpd
        file: >
            dest=/home/efthymiosh/.mpdconf
            src=/home/efthymiosh/.rice/.mpdconf
            state=link

      - name: install ncmpcpp
        pacman: name=ncmpcpp

      - name: config ncmpcpp
        file: >
            dest=/home/efthymiosh/.ncmpcpp
            src=/home/efthymiosh/.rice/.ncmpcpp
            state=link

      - name: install vifm
        pacman: name=vifm

      - name: config vifm
        file: >
            dest=/home/efthymiosh/.vifm
            src=/home/efthymiosh/.rice/.vifm
            state=link

      - name: install weechat
        pacman: name=weechat

      - name: config weechat
        file: >
            dest=/home/efthymiosh/.weechat
            src=/home/efthymiosh/.rice/.weechat
            state=link

      - name: install bitlbee
        pacman: name=bitlbee

      - name: install dzen2
        pacman: name=dzen2

      - name: install dmenu
        pacman: name=dmenu

      - name: install herbstluftwm
        pacman: name=herbstluftwm

      - name: herbstluft config dir
        file: >
            path=/home/efthymiosh/.config/herbstluftwm/
            state=directory

      - name: link herbstluftwm autostart
        file: >
            dest=/home/efthymiosh/.config/herbstluftwm/autostart
            src=/home/efthymiosh/.rice/.config/herbstluftwm/autostart
            state=link

      - name: link herbstluftwm icons folder
        file: >
            dest=/home/efthymiosh/.config/herbstluftwm/icons
            src=/home/efthymiosh/.rice/.config/herbstluftwm/icons
            state=link

      - name: link herbstluftwm panel.sh
        file: >
            dest=/home/efthymiosh/.config/herbstluftwm/panel.sh
            src=/home/efthymiosh/.rice/.config/herbstluftwm/panel.sh
            state=link
