- name: Configure arch desktop
  hosts: myhost
  become: True
  tasks:
      - name: config bashrc
        file: >
            dest=/home/efthymiosh/.bashrc
            src=/home/efthymiosh/.rice/.bashrc
            state=link

      - name: config screenrc
        file: >
            dest=/home/efthymiosh/.screenrc
            src=/home/efthymiosh/.rice/.screenrc
            state=link

      - name: config inputrc
        file: >
            dest=/home/efthymiosh/.inputrc
            src=/home/efthymiosh/.rice/.inputrc
            state=link

      - name: config bash aliases
        file: >
            dest=/home/efthymiosh/.bash_aliases
            src=/home/efthymiosh/.rice/.bash_aliases
            state=link

      - name: install nitrogen
        pacman: name=nitrogen update_cache=yes

      - name: install dunst
        pacman: name=dunst update_cache=yes

      - name: link dunst config folder
        file: >
            dest=/home/efthymiosh/.config/dunst
            src=/home/efthymiosh/.rice/.config/dunst
            state=link

      - name: install zathura
        pacman: name=zathura update_cache=yes

      - name: link zathura config folder
        file: >
            dest=/home/efthymiosh/.config/zathura
            src=/home/efthymiosh/.rice/.config/zathura
            state=link

      - name: install compton
        pacman: name=compton update_cache=yes

      - name: install rxvt-unicode
        pacman: name=rxvt-unicode update_cache=yes

      - name: config .Xdefaults
        command: cpp /home/efthymiosh/.rice/.Xdefaults -P -o ~/.Xdefaults 

      - name: install sxiv
        pacman: name=sxiv update_cache=yes

      - name: install vim
        pacman: name=vim update_cache=yes

      - name: link vimrc
        file: >
            dest=/home/efthymiosh/.vimrc
            src=/home/efthymiosh/.rice/.vimrc
            state=link

      - name: link vimdevrc
        file: >
            dest=/home/efthymiosh/.vimdevrc
            src=/home/efthymiosh/.rice/.vimdevrc
            state=link

      - name: install git
        pacman: name=git update_cache=yes

      - name: install xf86-input-synaptics
        pacman: name=xf86-input-synaptics update_cache=yes

      - name: install bash-completion
        pacman: name=bash-completion update_cache=yes

      - name: install mpd
        pacman: name=mpd update_cache=yes

      - name: config mpd
        file: >
            dest=/home/efthymiosh/.mpdconf
            src=/home/efthymiosh/.rice/.mpdconf
            state=link

      - name: install ncmpcpp
        pacman: name=ncmpcpp update_cache=yes

      - name: config ncmpcpp
        file: >
            dest=/home/efthymiosh/.ncmpcpp
            src=/home/efthymiosh/.rice/.ncmpcpp
            state=link

      - name: install vifm
        pacman: name=vifm update_cache=yes

      - name: config vifm
        file: >
            dest=/home/efthymiosh/.vifm
            src=/home/efthymiosh/.rice/.vifm
            state=link

      - name: install weechat
        pacman: name=weechat update_cache=yes

      - name: config weechat
        file: >
            dest=/home/efthymiosh/.weechat
            src=/home/efthymiosh/.rice/.weechat
            state=link

      - name: install bitlbee
        pacman: name=bitlbee update_cache=yes

      - name: install dzen2
        pacman: name=dzen2 update_cache=yes

      - name: install herbstluftwm
        pacman: name=herbstluftwm update_cache=yes

      - name: link herbstluftwm autostart
        file: >
            dest=/home/efthymiosh/.config/herbstluftwm/autostart
            src=/home/efthymiosh/.rice/.config/herbstluftwm/autostart
            state=link

      - name: link herbstluftwm icons folder
        file: >
            dest=/home/efthymiosh/.config/herbstluftwm/icons
            src=/home/efthymiosh/.rice/.config/herbstluftwm/icons
            state=link

      - name: link herbstluftwm panel.sh
        file: >
            dest=/home/efthymiosh/.config/herbstluftwm/panel.sh
            src=/home/efthymiosh/.rice/.config/herbstluftwm/panel.sh
            state=link

      - name: update AUR
        command: yaourt -Sy

      - name: install AUR packages
        command: yaourt -S urxvtcd alpine --noconfirm --needed

      - name: config mail addressbook
        file: >
            dest=/home/efthymiosh/.addressbook
            src=/home/efthymiosh/.rice/.addressbook
            state=link

      - name: config alpine
        file: >
            dest=/home/efthymiosh/.pinerc
            src=/home/efthymiosh/.rice/.pinerc
            state=link
