- name: Configure ubuntu desktop
  hosts: localhost
  become: true

  vars_files:
  - "vars/themes/dark/tokyonight_night.yml"
  - "vars/common.yml"

  vars:
    provision_hostname: "tile"
    x_cursor_theme: "Bibata-Modern-GrayBlue"

  pre_tasks:
  - name: update apt package information
    apt:
      update_cache: yes

  roles:
  - role: packages
    tags: packages
  - role: fonts
    tags: fonts
  - role: development
    tags: development
  - role: terminal
    tags: terminal
  - role: rofi
    tags: rofi
  - role: cursors
    tags: cursors
  - role: xdefaults
    tags: xdefaults
  - role: herbstluftwm
    tags: herbstluftwm
  - role: polybar
    tags: polybar
  - role: binpackages
    tags: binpackages

  tasks:
  - name: modify hostname
    hostname:
      name: "{{ provision_hostname }}"

  - name: completely disable power button
    become: true
    lineinfile:
      path: "/etc/systemd/logind.conf"
      regexp: '^#HandlePowerKey=poweroff'
      line: 'HandlePowerKey=ignore'
      owner: root
      group: root
      mode: '0644'
    notify: restart systemd-logind

  - name: completely disable suspend button
    become: true
    lineinfile:
      path: "/etc/systemd/logind.conf"
      regexp: '^#HandleSuspendKey=suspend'
      line: 'HandleSuspendKey=ignore'
      owner: root
      group: root
      mode: 0644
    notify: restart systemd-logind

  handlers:
  - name: restart systemd-logind
    become: true
    systemd:
      name: systemd-logind
      state: restarted
