- name: Configure ubuntu desktop
  hosts: localhost
  become: true

  vars_files:
  - "files/themes/dark/desert.yml"

  vars:
    home_folder: "/home/{{ ansible_env.SUDO_USER }}"
    provision_hostname: "bloomy"
    x_cursor_theme: "Bibata-Modern-Ice"
    alacritty_font_size: 9
    bitwarden_app_version: "1.28.2"
    bitwarden_cli_version: "1.18.0"
    terraform_version: "1.0.8"
    packer_version: "1.7.6"
    waypoint_version: "0.5.2"
    fluvio_version: "0.9.9"
    glab_version: "1.21.1"

  pre_tasks:
  - name: update apt package information
    apt:
      update_cache: yes

  roles:
  - role: packages
    tags: packages
  - role: fira-code
    tags: fira-code
  - role: development
    tags: development
  - role: alacritty
    tags: alacritty
  - role: rofi
    tags: rofi
  - role: cursors
    tags: cursors
  - role: xdefaults
    tags: xdefaults
  - role: herbstluftwm
    tags: herbstluftwm
  - role: polybar
    tags: polybar
  - role: bitwarden
    tags: bitwarden
  - role: 1password
    tags: 1password
  - role: binpackages
    tags: binpackages

  tasks:
  - name: modify hostname
    hostname:
      name: "{{ provision_hostname }}"

  - name: completely disable power button
    become: true
    lineinfile:
      path: "/etc/systemd/logind.conf"
      regexp: '^#HandlePowerKey=poweroff'
      line: 'HandlePowerKey=ignore'
      owner: root
      group: root
      mode: '0644'
    notify: restart systemd-logind

  - name: completely disable suspend button
    become: true
    lineinfile:
      path: "/etc/systemd/logind.conf"
      regexp: '^#HandleSuspendKey=suspend'
      line: 'HandleSuspendKey=ignore'
      owner: root
      group: root
      mode: 0644
    notify: restart systemd-logind

  handlers:
  - name: restart systemd-logind
    become: true
    systemd:
      name: systemd-logind
      state: restarted
