- name: Configure ubuntu desktop
  hosts: localhost
  become: true

  vars_files:
  - "./vars/themes/dark/catpuccin_mochaer.yml"
  - "./vars/common.yml"

  vars:
    provision_hostname: "tile"
    x_cursor_theme: "Bibata-Modern-Catpuccin-Mocha"
    global_font: "Fira Code Nerd Font"
    alacritty_font_size: 10.5

  pre_tasks:
  - name: update apt package information
    apt:
      update_cache: yes

  roles:
  - role: packages
    tags: packages
  - role: development
    tags: development
  - role: terminal
    tags: terminal
  - role: desktop_linux
    tags: desktop

  tasks:
  - name: modify hostname
    hostname:
      name: "{{ provision_hostname }}"

  # The Asus ROG Falchion sends power and suspend button presses to the pc
  # whenever it itself suspends, causing chaos.
  # source: https://gist.github.com/jnettlet/afb20a048b8720f3b4eb8506d8b05643
  - name: work around rog falchion sending power and suspend signals
    copy:
      src: "./files/99-asus-falchion.hwdb"
      dest: "/etc/udev/hwdb.d/99-asus-falchion.hwdb"
      owner: root
      group: root
      mode: '0644'
