- name: Configure ubuntu desktop
  hosts: localhost
  become: true

  vars_files:
  - "files/themes/dark/spacegray.yml"

  vars:
    home_folder: "/home/{{ ansible_env.SUDO_USER }}"
    provision_hostname: "tile"
    x_cursor_theme: "Bibata-Modern-Classic"
    alacritty_version: "0.9.0"
    bitwarden_app_version: "1.28.2"
    bitwarden_cli_version: "1.18.0"

  pre_tasks:
  - name: update apt package information
    apt:
      update_cache: yes

  roles:
  - role: packages
    tags: packages
  - role: fira-code
    tags: fira-code
  - role: development
    tags: development
  - role: alacritty
    tags: alacritty
  - role: rofi
    tags: rofi
  - role: cursors
    tags: cursors
  - role: xdefaults
    tags: xdefaults
  - role: herbstluftwm
    tags: herbstluftwm
  - role: polybar
    tags: polybar
  - role: bitwarden
    tags: bitwarden
  - role: 1password
    tags: 1password
  - role: binpackage
    tags: terraform
    vars:
      package_name: terraform
      package_version: "1.0.8"
      package_fetch_url: "https://releases.hashicorp.com/terraform/{{ package_version }}/terraform_{{ package_version }}_linux_amd64.zip"
      package_exe_subpath_dir: ""
  - role: binpackage
    tags: packer
    vars:
      package_name: packer
      package_version: "1.7.6"
      package_fetch_url: "https://releases.hashicorp.com/packer/{{ package_version }}/packer_{{ package_version }}_linux_amd64.zip"
      package_exe_subpath_dir: ""
  - role: binpackage
    tags: waypoint
    vars:
      package_name: waypoint
      package_version: "0.5.2"
      package_fetch_url: "https://releases.hashicorp.com/waypoint/{{ package_version }}/waypoint_{{ package_version }}_linux_amd64.zip"
      package_exe_subpath_dir: ""
  - role: binpackage
    tags: fluvio
    vars:
      package_name: fluvio
      package_version: "0.9.9"
      package_fetch_url: "https://github.com/infinyon/fluvio/releases/download/v{{ package_version }}/fluvio-x86_64-unknown-linux-musl.zip"
      package_exe_subpath_dir: ""
  - role: binpackage
    tags: glab
    vars:
      package_name: glab
      package_version: "1.21.1"
      package_fetch_url: "https://github.com/profclems/glab/releases/download/v{{ package_version }}/glab_{{ package_version }}_Linux_x86_64.tar.gz"
      package_exe_subpath_dir: "bin"

  tasks:
  - name: modify hostname
    hostname:
      name: "{{ provision_hostname }}"

  - name: completely disable power button
    become: true
    lineinfile:
      path: "/etc/systemd/logind.conf"
      regexp: '^#HandlePowerKey=poweroff'
      line: 'HandlePowerKey=ignore'
      owner: root
      group: root
      mode: '0644'
    notify: restart systemd-logind

  - name: completely disable suspend button
    become: true
    lineinfile:
      path: "/etc/systemd/logind.conf"
      regexp: '^#HandleSuspendKey=suspend'
      line: 'HandleSuspendKey=ignore'
      owner: root
      group: root
      mode: 0644
    notify: restart systemd-logind

  handlers:
  - name: restart systemd-logind
    become: true
    systemd:
      name: systemd-logind
      state: restarted
