- name: Configure ubuntu desktop
  hosts: localhost
  become: true

  vars_files:
  - "files/themes/dark/termsexy_gray.yml"

  vars:
    home_folder: "/home/{{ ansible_env.SUDO_USER }}"
    rice_location: "{{ home_folder }}/cloned/rice"
    provision_hostname: "bloomy"
    polybar_version: "3.5.4"
    polybar_thermal_zone: "6"
    x_cursor_theme: "Pop"
    x_cursor_size: "24"
    alacritty_version: "0.9.0"
    bitwarden_app_version: "1.28.2"
    bitwarden_cli_version: "1.18.0"

  roles:
  - role: fira-code
    tags: fira-code
  - role: vim
    tags: vim
  - role: alacritty
    tags: alacritty
  - role: rofi
    tags: rofi
  - role: cursors
    tags: cursors
  - role: xdefaults
    tags: xdefaults
  - role: herbstluftwm
    tags: herbstluftwm
  - role: polybar
    tags: polybar
  - role: bitwarden
    tags: bitwarden
  - role: 1password
    tags: 1password

  pre_tasks:
  - name: update apt package information
    apt:
      update_cache: yes

  tasks:
  - name: install packages
    apt:
      name: [
        "build-essential", "chromium-browser", "alpine", "dunst",
        "zathura", "tree", "screen", "curl", "pavucontrol", "gimp",
        "jq", "ripgrep", "lm-sensors", "htop", "perf-tools-unstable",
        "pssh"
      ]
      state: present
      update_cache: no

  - name: set file configuration
    become: false
    copy:
      dest: "{{ home_folder }}/.{{ item }}"
      src:  "files/{{ item }}"
    with_items:
    - "bashrc"
    - "bash_aliases"
    - "screenrc"
    - "inputrc"
    - "pinerc"

  - name: set directory configuration
    become: false
    copy:
      dest: "{{ home_folder }}/.config/"
      src:  "files/config/{{ item }}"
    with_items:
    - "dunst"
    - "zathura"

  - name: modify hostname
    hostname:
      name: "{{ provision_hostname }}"

  - name: completely disable power button
    become: true
    lineinfile:
      path: "/etc/systemd/logind.conf"
      regexp: '^#HandlePowerKey=poweroff'
      line: 'HandlePowerKey=ignore'
      owner: root
      group: root
      mode: '0644'
    notify: restart systemd-logind

  - name: completely disable suspend button
    become: true
    lineinfile:
      path: "/etc/systemd/logind.conf"
      regexp: '^#HandleSuspendKey=suspend'
      line: 'HandleSuspendKey=ignore'
      owner: root
      group: root
      mode: 0644
    notify: restart systemd-logind

  - name: link parallel-ssh to pssh
    become: true
    file:
      path: "/usr/bin/pssh"
      src: "/usr/bin/parallel-ssh"
      state: "link"
      owner: root
      group: root
      mode: 0755

  handlers:
  - name: restart systemd-logind
    become: true
    systemd:
      name: systemd-logind
      state: restarted
