- name: Configure ubuntu desktop
  hosts: localhost
  become: true

  vars_files:
  - "files/themes/dark/tokyonight_night.yml"

  vars:
    home_folder: "/home/{{ ansible_env.SUDO_USER }}"
    provision_hostname: "tile"
    x_cursor_theme: "Bibata-Modern-GrayBlue"
    bitwarden_app_version: "2022.6.1"
    bitwarden_cli_version: "1.22.1"
    terraform_version: "1.2.4"
    packer_version: "1.8.2"
    waypoint_version: "0.9.0"
    fluvio_version: "0.9.30"
    glab_version: "1.22.0"
    starship_version: "1.9.1"
    consul_version: "1.12.2"
    nomad_version: "1.3.1"
    zellij_version: "0.23.0"

  pre_tasks:
  - name: update apt package information
    apt:
      update_cache: yes

  roles:
  - role: packages
    tags: packages
  - role: fonts
    tags: fonts
  - role: development
    tags: development
  - role: terminal
    tags: terminal
  - role: rofi
    tags: rofi
  - role: cursors
    tags: cursors
  - role: xdefaults
    tags: xdefaults
  - role: herbstluftwm
    tags: herbstluftwm
  - role: polybar
    tags: polybar
  - role: bitwarden
    tags: bitwarden
  - role: 1password
    tags: 1password
  - role: binpackages
    tags: binpackages

  tasks:
  - name: modify hostname
    hostname:
      name: "{{ provision_hostname }}"

  - name: completely disable power button
    become: true
    lineinfile:
      path: "/etc/systemd/logind.conf"
      regexp: '^#HandlePowerKey=poweroff'
      line: 'HandlePowerKey=ignore'
      owner: root
      group: root
      mode: '0644'
    notify: restart systemd-logind

  - name: completely disable suspend button
    become: true
    lineinfile:
      path: "/etc/systemd/logind.conf"
      regexp: '^#HandleSuspendKey=suspend'
      line: 'HandleSuspendKey=ignore'
      owner: root
      group: root
      mode: 0644
    notify: restart systemd-logind

  handlers:
  - name: restart systemd-logind
    become: true
    systemd:
      name: systemd-logind
      state: restarted
