- name: install zoxide, fzf, starship
  include_role:
    name: packages/binpackages
  vars:
    binpackages_items:
    - name: zoxide
      version: "{{ zoxide_version }}"
      fetch_url: "https://github.com/ajeetdsouza/zoxide/releases/download/v{{ zoxide_version }}/zoxide-{{ zoxide_version }}-{{ alt_arch }}-{{ vendor }}-{{ system }}{{ iflinux_musl }}.tar.gz"
    - name: fzf
      version: "{{ fzf_version }}"
      fetch_url: "https://github.com/junegunn/fzf/releases/download/v{{ fzf_version }}/fzf-{{ fzf_version }}-{{ system }}_{{ real_arch }}.tar.gz"
    - name: starship
      version: "{{ starship_version }}"
      fetch_url: "https://github.com/starship/starship/releases/download/v{{ starship_version }}/starship-{{ alt_arch }}-{{ vendor }}-{{system}}{{ iflinux_gnu }}.tar.gz"


- name: fetch and install terminal emulators
  become: "{{ package_manager_become }}"
  homebrew_cask:
    name: [ "alacritty", "ghostty" ]
