- import_tasks: alacritty.yml
  tags: alacritty

- import_tasks: starship.yml
  tags: starship

- name: fetch and install terminal packages
  apt:
    name:
    - "screen"
    - "tmux"
    - "zsh"

- name: install zoxide,fzf
  include_role:
    name: binpackages
  vars:
    binpackages_items:
    - name: zoxide
      version: "{{ zoxide_version }}"
      fetch_url: "https://github.com/ajeetdsouza/zoxide/releases/download/v{{ zoxide_version }}/zoxide-{{ zoxide_version }}-x86_64-unknown-linux-musl.tar.gz"
    - name: fzf
      version: "{{ fzf_version }}"
      fetch_url: "https://github.com/junegunn/fzf/releases/download/{{ fzf_version }}/fzf-{{ fzf_version }}-linux_amd64.tar.gz"


- name: set terminal file configuration
  become: false
  copy:
    dest: "{{ home_folder }}/.{{ item }}"
    src:  "files/{{ item }}"
  loop:
  - "bash_aliases"
  - "screenrc"
  - "inputrc"
  - "zshrc"
  - "ssh-agent.zsh"

- name: template terminal configuration
  become: false
  template:
    dest: "{{ home_folder }}/.{{ item }}"
    src: "templates/{{ item }}.j2"
  loop: 
  - "bashrc"
  - "tmux.conf"
  tags: theme

- name: ensure user default shell is set
  become: true
  user:
    name: "{{ default_user }}"
    shell: "/bin/{{ default_shell }}"
