- include_tasks: "{{ ansible_os_family }}.yml"

- name: ensure config directories exist
  become: false
  file:
    path: "{{ home_folder }}/.config/{{ item }}"
    state: directory
  loop:
  - alacritty
  - ghostty

- name: template {{ item.name }} configuration
  become: false
  template:
    src: "templates/{{ item.src }}"
    dest: "{{ home_folder }}/.config/{{ item.dest }}"
  loop:
  - name: starship
    src: "starship.toml.j2"
    dest: "starship.toml"
  - name: "alacritty  >= 0.13"
    src: "alacritty.j2.toml"
    dest: "alacritty/alacritty.toml"
  - name: "alacritty  < 0.13"
    src: "alacritty.j2.yml"
    dest: "alacritty/alacritty.yml"
  - name: "ghostty"
    src: "ghostty/config.j2"
    dest: "ghostty/config"
  tags: theme

- name: fetch and install terminal packages
  become: "{{ package_manager_become }}"
  package:
    name:
    - "tmux"
    - "zsh"

- name: set terminal file configuration
  become: false
  copy:
    dest: "{{ home_folder }}/.{{ item }}"
    src:  "files/{{ item }}"
  loop:
  - "bash_aliases"
  - "inputrc"
  - "ssh-agent.zsh"

- name: template terminal configuration
  become: false
  template:
    dest: "{{ home_folder }}/.{{ item }}"
    src: "templates/{{ item }}.j2"
  loop: 
  - "zshrc"
  - "tmux.conf"
  tags: theme

- name: ensure user default shell is set
  become: true
  user:
    name: "{{ default_user }}"
    shell: "/bin/{{ default_shell }}"
