- import_tasks: alacritty.yml
  tags: alacritty

- import_tasks: starship.yml
  tags: starship

- name: fetch and install terminal packages
  apt:
    name: [ "screen", "tmux", "zsh" ]

- name: set terminal file configuration
  become: false
  copy:
    dest: "{{ home_folder }}/.{{ item }}"
    src:  "files/{{ item }}"
  loop:
  - "bash_aliases"
  - "screenrc"
  - "inputrc"
  - "zshrc"

- name: template terminal configuration
  become: false
  template:
    dest: "{{ home_folder }}/.{{ item }}"
    src: "templates/{{ item }}.j2"
  loop: 
  - "bashrc"
  - "tmux.conf"
  tags: theme

- name: ensure user default terminal
  become: true
  user:
    name: "{{ default_user }}"
    shell: "/bin/zsh"
