- name: install starship
  include_role:
    name: packages/binpackages
  vars:
    binpackages_items:
    - name: starship
      version: "{{ starship_version }}"
      fetch_url: "https://github.com/starship/starship/releases/download/v{{ starship_version }}/starship-{{ alt_arch }}-{{ vendor }}-{{system}}{{ iflinux_gnu }}.tar.gz"

- name: template starship configuration
  become: false
  template:
    dest: "{{ home_folder }}/.config/{{ item }}"
    src: "templates/{{ item }}.j2"
  loop:
  - "starship.toml"
