alias git-log='git log --oneline --decorate --graph --all'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias diff='diff --color=auto'
alias rg='rg --hidden --max-columns 200'
alias less='less -R'
alias ls='ls --literal --color=auto'
alias ll='ls --literal --color=auto -l'
alias info='info --vi-keys'

alias vim='nvim'
alias myip='dig @resolver1.opendns.com myip.opendns.com +short'
alias fixdns='sudo systemd-resolve -i wlp0s20f3 --set-dns=1.1.1.1'

alias pssh='parallel-ssh'

function git-clean {
    git branch --merged | grep -ve '*' -e '^[ ]*master$' -e '^[ ]main*' | xargs git branch -d
}
