HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000

source ~/.ssh-agent.zsh
setopt autocd beep nomatch share_history
unsetopt extendedglob notify
bindkey -v
bindkey "^R" history-incremental-pattern-search-backward

zstyle :compinstall filename '/home/ehadjimichael/.zshrc'
autoload -Uz compinit
compinit

if [ -f ~/.bash_aliases ]; then
    source ~/.bash_aliases
fi

eval "$(starship init zsh)"
