HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000

source ~/.ssh-agent.zsh
setopt autocd beep nomatch share_history
unsetopt extendedglob notify
bindkey -v
bindkey "^R" history-incremental-pattern-search-backward

zstyle :compinstall filename '/home/ehadjimichael/.zshrc'
autoload -Uz compinit
compinit

if [ -f ~/.bash_aliases ]; then
    source ~/.bash_aliases
fi

if [ -f ~/.env ]; then
    source ~/.env
fi

autoload edit-command-line; zle -N edit-command-line
autoload -U +X bashcompinit && bashcompinit

complete -o nospace -C /opt/consul/consul consul
complete -o nospace -C /opt/nomad/nomad nomad

bindkey -M vicmd v edit-command-line

eval "$(zoxide init zsh)"
eval "$(starship init zsh)"
