theme:
  foreground: 'cdd6f4'
  background: '181825'
  normal:
    black: "1e1e2e"
    red: "eba0ac"
    green: "a6e3a1"
    yellow: "f9e2af"
    blue: "89b4fa"
    magenta: "cba6f7"
    cyan: "94e2d5"
    white: "bac2de"
  bright:
    black: "484b60"
    red: "f38ba8"
    green: "a6e3a1"
    yellow: "fab387"
    blue: "89dceb"
    magenta: "f5c2e7"
    cyan: "94e2d5"
    white: "a6adc8"
  accent: 'f5e0dc'
  accent_text: '1e1e2e'
