[general]
live_config_reload = true

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black   = "0x{{ theme.bright.black }}"
red     = "0x{{ theme.bright.red }}"
green   = "0x{{ theme.bright.green }}"
yellow  = "0x{{ theme.bright.yellow }}"
blue    = "0x{{ theme.bright.blue }}"
magenta = "0x{{ theme.bright.magenta }}"
cyan    = "0x{{ theme.bright.cyan }}"
white   = "0x{{ theme.bright.white }}"

[colors.cursor]
text   = "0x{{ theme.accent_text }}"
cursor = "0x{{ theme.accent }}"

[colors.normal]
black   = "0x{{ theme.normal.black }}"
red     = "0x{{ theme.normal.red }}"
green   = "0x{{ theme.normal.green }}"
yellow  = "0x{{ theme.normal.yellow }}"
blue    = "0x{{ theme.normal.blue }}"
magenta = "0x{{ theme.normal.magenta }}"
cyan    = "0x{{ theme.normal.cyan }}"
white   = "0x{{ theme.normal.white }}"

[colors.primary]
background = "0x{{ theme.background }}"
foreground = "0x{{ theme.foreground }}"

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
persistent_logging = false
render_timer = false

[font]
size = {{ alacritty_font_size }}

[font.bold]
family = "{{ global_font }}"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "{{ global_font }}"
style = "Light"

[font.normal]
family = "{{ global_font }}"
style = "Regular"

[font.offset]
x = {% if system == "darwin" %}0{% else %}-1{% endif +%}
y = {% if system == "darwin" %}0{% else %}-2{% endif +%}

[[hints.enabled]]
command = "{% if system != 'darwin' %}xdg-{% endif %}open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
dynamic_padding = true
dynamic_title = true
opacity = 1.0
startup_mode = "Windowed"
{% if system == 'darwin' %}
option_as_alt = "Both"
decorations = "buttonless"
{% endif %}

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0
