- name: install cask packages
  become: false
  homebrew_cask:
    name:
    - "font-fira-code-nerd-font"
    - "font-fira-mono-nerd-font"
    - "font-mononoki-nerd-font"
    - "font-space-mono-nerd-font"
